---
AWSTemplateFormatVersion: "2010-09-09"

Description: "Deploys the mux video monitor"

Parameters:
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
  AppDomain:
    Type: String
  # BackendLambdaS3Bucket:
  #   Type: String
  # BackendLambdaS3Key:
  #   Type: String

Resources:
  AppCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Sub "${AppDomain}"
      DomainValidationOptions:
        - DomainName: !Sub "${AppDomain}"
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: "DNS"

  FrontendWebsite:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "PublicRead"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "index.html"
  
  FrontendWebsiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref "FrontendWebsite"
      PolicyDocument:
        "Version": "2012-10-17"
        "Statement":
        - "Effect": "Allow"
          "Principal": "*"
          "Action":
          - "s3:GetObject"
          "Resource":
          - !Sub "arn:aws:s3:::${FrontendWebsite}/*"

  # FrontendDistribution:
  #   Type: "AWS::CloudFront::Distribution"
  #   Properties:
  #     DistributionConfig:
  #       Aliases:
  #       - !Ref AppDomain
  #       CacheBehaviors:
  #       - AllowedMethods:
  #         - "GET"
  #         - "HEAD"
  #         CachedMethods:
  #         - "GET"
  #         - "HEAD"
  #         CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad" # "Managed-CachingDisabled"
  #         Compress: true
  #         PathPattern: "index.html"
  #         TargetOriginId: !Sub "${AWS::StackName}-FrontendOrigin"
  #         ViewerProtocolPolicy: "redirect-to-https"
  #       - AllowedMethods:
  #         - "GET"
  #         - "HEAD"
  #         - "POST"
  #         - "OPTIONS"
  #         - "DELETE"
  #         - "PUT"
  #         - "PATCH"
  #         CachedMethods:
  #         - "GET"
  #         - "HEAD"
  #         CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad" # "Managed-CachingDisabled"
  #         Compress: true
  #         PathPattern: "/api/*"
  #         TargetOriginId: !Sub "${AWS::StackName}-BackendOrigin"
  #         ViewerProtocolPolicy: "redirect-to-https"
  #       DefaultRootObject: "index.html"
  #       DefaultCacheBehavior:
  #         AllowedMethods:
  #         - "GET"
  #         - "HEAD"
  #         CachedMethods:
  #         - "GET"
  #         - "HEAD"
  #         CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" # "Managed-CachingOptimized"
  #         Compress: true
  #         TargetOriginId: !Sub "${AWS::StackName}-FrontendOrigin"
  #         ViewerProtocolPolicy: "redirect-to-https"
  #       Enabled: true
  #       HttpVersion: "http2"
  #       IPV6Enabled: true
  #       Origins:
  #       - CustomOriginConfig:
  #           OriginProtocolPolicy: "http-only"
  #         DomainName: !Sub "${FrontendWebsite}.s3-website-${AWS::Region}.amazonaws.com"
  #         Id: !Sub "${AWS::StackName}-FrontendOrigin"
  #       - CustomOriginConfig:
  #           OriginProtocolPolicy: "https-only"
  #         DomainName: !Sub ${BackendAPI}.execute-api.${AWS::Region}.amazonaws.com
  #         Id: !Sub "${AWS::StackName}-BackendOrigin"
  #       PriceClass: 'PriceClass_All'
  #       ViewerCertificate:
  #         AcmCertificateArn: !Ref 'FrontendWebsiteCertificate'
  #         MinimumProtocolVersion: 'TLSv1.1_2016'
  #         SslSupportMethod: 'sni-only'

  # SecondDNSIPv4:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     AliasTarget:
  #       DNSName: !GetAtt "FrontendDistribution.DomainName"
  #       HostedZoneId: "Z2FDTNDATAQYW2"
  #     HostedZoneId: !Ref "HostedZoneId"
  #     Name: !Ref "AppDomain"
  #     Type: "A"

  # SecondDNSIPv6:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     AliasTarget:
  #       DNSName: !GetAtt "FrontendDistribution.DomainName"
  #       HostedZoneId: "Z2FDTNDATAQYW2"
  #     HostedZoneId: !Ref "HostedZoneId"
  #     Name: !Ref "AppDomain"
  #     Type: "AAAA"

Outputs:
  # FrontendURL:
  #   Value: !GetAtt "FrontendDistribution.DomainName"
  FrontendWebsiteBucket:
    Value: !Ref "FrontendWebsite"
