Parameters:
  RepoName:
    Type: String
    Default: thepatrick/mux-video-monitor
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: ""
    Type: String

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MuxVideoMonitorGithubRole
      ManagedPolicyArns: [arn:aws:iam::aws:policy/AdministratorAccess]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref OIDCProviderArn
            Condition:
              StringLike:
                "token.actions.githubusercontent.com:aud": "https://github.com/thepatrick"
                "token.actions.githubusercontent.com:sub": !Sub repo:${RepoName}:ref:refs/heads/main

Outputs:
  Role:
    Value: !GetAtt Role.Arn
