# .github/workflows/example.yml
name: Mux Video Monitor

on:
  push:
    branches:
      - main

env:
  HOSTED_ZONE_ID: Z09102521YXWQT2ZKMPP7
  APP_DOMAIN: mux-monitor.aws.nextdayvideo.com.au

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    outputs:
      frontendBucket: ${{ steps.deploy.outputs.frontendBucket }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - run: sleep 5 # there's still a race condition for now

      - name: Configure AWS
        run: ./ci/configure-aws.sh

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2 # default
          verbose: false # default
          
      - name: Deploy deployment.cfn.yaml
        id: deploy
        run: |
          ./infra/deploy.sh
